# Generated by Django 6.0.7 on 2026-07-14 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=120, verbose_name='Nombre del cliente')),
                ('telefono', models.CharField(max_length=30, verbose_name='Teléfono / WhatsApp')),
                ('servicio', models.CharField(choices=[('mantenimiento', 'Mantenimiento general'), ('aceite', 'Cambio de aceite y filtro'), ('frenos', 'Revisión de frenos'), ('inyeccion', 'Diagnóstico de inyección'), ('otro', 'Otro')], default='mantenimiento', max_length=20)),
                ('moto', models.CharField(blank=True, max_length=100, verbose_name='Moto (modelo/placa)')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('hora', models.TimeField(verbose_name='Hora')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente por confirmar'), ('confirmada', 'Confirmada'), ('atendida', 'Atendida'), ('cancelada', 'Cancelada')], default='pendiente', max_length=15)),
                ('notas', models.TextField(blank=True)),
                ('creada', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cita de taller',
                'verbose_name_plural': 'Citas de taller',
                'ordering': ['fecha', 'hora'],
            },
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(blank=True, max_length=120, verbose_name='Nombre del cliente')),
                ('telefono', models.CharField(blank=True, max_length=30, verbose_name='Teléfono / WhatsApp')),
                ('estado', models.CharField(choices=[('nueva', 'Nueva'), ('contactado', 'Cliente contactado'), ('vendida', 'Vendida'), ('vencida', 'Vencida')], default='nueva', max_length=15)),
                ('origen', models.CharField(default='web', max_length=20)),
                ('creada', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cotización',
                'verbose_name_plural': 'Cotizaciones',
                'ordering': ['-creada'],
            },
        ),
        migrations.CreateModel(
            name='ImportacionInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='importaciones/')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('creados', models.PositiveIntegerField(default=0)),
                ('actualizados', models.PositiveIntegerField(default=0)),
                ('errores', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Importación de inventario',
                'verbose_name_plural': 'Importaciones de inventario',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_celeste', models.CharField(max_length=30, unique=True, verbose_name='Código Celeste')),
                ('referencia', models.CharField(blank=True, db_index=True, max_length=40, verbose_name='Referencia Honda')),
                ('nombre', models.CharField(max_length=250, verbose_name='Nombre')),
                ('descripcion_original', models.CharField(blank=True, max_length=300, verbose_name='Descripción original (Celeste)')),
                ('categoria', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Categoría')),
                ('marca', models.CharField(default='Honda', max_length=60, verbose_name='Marca')),
                ('precio', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Precio público')),
                ('stock', models.IntegerField(default=0, verbose_name='Stock disponible')),
                ('modelos_compatibles', models.CharField(blank=True, help_text='Separados por coma. Se llena automático al importar; se puede corregir a mano.', max_length=250, verbose_name='Modelos compatibles')),
                ('activo', models.BooleanField(default=True, verbose_name='Visible en la web')),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ItemCotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=0, max_digits=12)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tienda.cotizacion')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tienda.producto')),
            ],
            options={
                'verbose_name': 'Ítem de cotización',
                'verbose_name_plural': 'Ítems de cotización',
            },
        ),
        migrations.CreateModel(
            name='VentaRapida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='tienda.producto')),
            ],
            options={
                'verbose_name': 'Venta rápida (mostrador)',
                'verbose_name_plural': 'Ventas rápidas (mostrador)',
                'ordering': ['-fecha'],
            },
        ),
    ]
