# Generated by Django 6.0.7 on 2026-08-31 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/', verbose_name='Foto del producto'),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen_url',
            field=models.URLField(blank=True, help_text='Pega el enlace de una imagen si no quieres subir archivo', verbose_name='Foto por URL'),
        ),
    ]
