# Generated by Django 6.0.7 on 2026-08-31 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_producto_imagen_producto_imagen_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSitio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_asesor', models.CharField(default='57', help_text='Solo números con indicativo, ej: 573001234567', max_length=20, verbose_name='WhatsApp del asesor')),
                ('nombre_asesor', models.CharField(blank=True, default='Asesor comercial', max_length=80)),
            ],
            options={
                'verbose_name': 'Configuración del sitio',
                'verbose_name_plural': 'Configuración del sitio',
            },
        ),
        migrations.CreateModel(
            name='Motocicleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, verbose_name='Modelo')),
                ('marca', models.CharField(default='Honda', max_length=60)),
                ('precio', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('cilindraje', models.CharField(blank=True, max_length=30)),
                ('categoria', models.CharField(blank=True, help_text='naked, enduro, scooter, semiautomática, etc.', max_length=40)),
                ('descripcion', models.TextField(blank=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='motos/', verbose_name='Foto principal')),
                ('imagen_url', models.URLField(blank=True, verbose_name='Foto por URL')),
                ('destacada', models.BooleanField(default=False, verbose_name='Mostrar como destacada')),
                ('disponible', models.BooleanField(default=True, verbose_name='Disponible')),
                ('orden', models.PositiveIntegerField(default=100, help_text='Menor número aparece primero')),
            ],
            options={
                'verbose_name': 'Motocicleta',
                'verbose_name_plural': 'Motocicletas',
                'ordering': ['orden', 'precio'],
            },
        ),
    ]
