# Generated by Django 6.0.7 on 2026-09-05 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_configuracionsitio_motocicleta'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='texto_busqueda',
            field=models.TextField(blank=True, db_index=True, editable=False, help_text='Se recalcula solo en save(); no editar a mano.', verbose_name='Texto de búsqueda (uso interno)'),
        ),
    ]
