# Generated by Django 6.0.7 on 2026-09-06 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0006_texto_busqueda_sin_indice'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='asesor',
            field=models.CharField(blank=True, max_length=80, verbose_name='Asesor que la tomó'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='motivo_perdida',
            field=models.CharField(blank=True, choices=[('sin_stock', 'Sin stock real'), ('precio', 'Precio'), ('no_contesto', 'No contestó'), ('otro_lado', 'Compró en otro lado'), ('otro', 'Otro')], max_length=20, verbose_name='Motivo de pérdida'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='notas_asesor',
            field=models.TextField(blank=True, verbose_name='Notas del asesor'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='tomada_en',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Tomada el'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='estado',
            field=models.CharField(choices=[('nueva', 'Nueva'), ('tomada', 'Tomada'), ('vendida', 'Vendida'), ('perdida', 'Perdida')], default='nueva', max_length=15),
        ),
    ]
