# Generated by Django 6.0.7 on 2026-09-09 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0008_migrar_estados_cotizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsitio',
            name='direccion',
            field=models.CharField(blank=True, help_text='Se usa en el pie de página, la sección de taller y como alternativa al WhatsApp. Opcional.', max_length=200, verbose_name='Dirección del almacén'),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='telefono_fijo',
            field=models.CharField(blank=True, help_text='Alternativa visible cuando el WhatsApp no está disponible. Opcional.', max_length=30, verbose_name='Teléfono fijo del almacén'),
        ),
        migrations.AlterField(
            model_name='configuracionsitio',
            name='whatsapp_asesor',
            field=models.CharField(blank=True, help_text='Solo dígitos, con indicativo de país: 10 a 15. Ej: 573001234567. Si queda vacío o mal, el sitio oculta el botón de WhatsApp y muestra el teléfono fijo / la dirección en su lugar.', max_length=20, verbose_name='WhatsApp del asesor'),
        ),
    ]
