# Generated by Django 6.0.7 on 2026-09-11 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0010_reparsear_nombres'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='resuelta_en',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Resuelta el'),
        ),
    ]
