"""
Django settings for supermotos_backend project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Carga variables de un .env local si existe (nunca se commitea). En Railway
# las variables ya vienen del entorno, así que esto simplemente no hace nada.
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# La clave real vive SOLO en la variable de entorno SECRET_KEY (local: en tu
# shell o en un .env que NUNCA se commitea; en Railway: en sus Variables).
# Este valor de respaldo es a propósito uno "inseguro" y genérico -- nunca
# debe usarse en producción -- para que el proyecto igual arranque en un
# entorno de desarrollo nuevo sin configuración extra.
SECRET_KEY = os.environ.get(
    'SECRET_KEY',
    'django-insecure-solo-para-desarrollo-local-configura-SECRET_KEY-en-produccion',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Se resuelve más abajo, después de detectar el entorno de producción
# (ver bloque "Configuración del proyecto SuperMotos" al final del archivo).
ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'rest_framework',
    'corsheaders',
    'tienda',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'supermotos_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'supermotos_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Si existe DATABASE_URL (Railway con Postgres) se usa esa; si no, sigue
# usando SQLite local como hasta ahora. El disco de Railway es efímero, por
# eso en producción SIEMPRE debe estar configurada esta variable.
if os.environ.get('DATABASE_URL'):
    DATABASES = {
        'default': dj_database_url.parse(os.environ['DATABASE_URL']),
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'es-co'

TIME_ZONE = 'America/Bogota'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'
# Django 6 NO completa las claves que falten: hay que declarar 'default'
# explícitamente o cualquier escritura de FileField (subir el Excel de Celeste,
# una foto de producto) revienta con InvalidStorageError.
STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}


# --- Configuración del proyecto SuperMotos ---

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Producción (Railway u otro host): variables de entorno. Se resuelve ANTES
# de CORS/ALLOWED_HOSTS para que ambos queden calculados con el DEBUG final.
if os.environ.get('RAILWAY_ENVIRONMENT'):
    DEBUG = False
    CSRF_TRUSTED_ORIGINS = [os.environ.get('CSRF_ORIGIN', 'https://*.up.railway.app')]

# Lista separada por comas, ej: "supermotos.com,www.supermotos.com". Vacía en
# desarrollo: con DEBUG=True, Django igual permite localhost/127.0.0.1.
ALLOWED_HOSTS = [h.strip() for h in os.environ.get('ALLOWED_HOSTS', '').split(',') if h.strip()]

# Railway publica el dominio del servicio en RAILWAY_PUBLIC_DOMAIN (p.ej.
# "supermotos-production.up.railway.app"). Se agrega solo, para que el sitio y
# el healthcheck respondan sin tener que copiar el dominio a mano en las
# variables. Un dominio propio sí hay que ponerlo en ALLOWED_HOSTS.
_railway_domain = os.environ.get('RAILWAY_PUBLIC_DOMAIN', '').strip()
if _railway_domain and _railway_domain not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(_railway_domain)
    _csrf = globals().get('CSRF_TRUSTED_ORIGINS', [])
    if 'https://' + _railway_domain not in _csrf:
        CSRF_TRUSTED_ORIGINS = _csrf + ['https://' + _railway_domain]

# En desarrollo se permite cualquier origen; en producción, solo los dominios
# reales en CORS_ALLOWED_ORIGINS (misma lista separada por comas).
CORS_ALLOW_ALL_ORIGINS = DEBUG
if not DEBUG:
    CORS_ALLOWED_ORIGINS = [o.strip() for o in os.environ.get('CORS_ALLOWED_ORIGINS', '').split(',') if o.strip()]

REST_FRAMEWORK = {
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.ScopedRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '120/min',
        # Cotizaciones y citas: límite aparte y más estricto para que no
        # spameen el calendario/las cotizaciones del almacén. Los catálogos
        # de lectura (productos, motos) siguen solo con el límite 'anon'.
        'escritura_publica': '5/hour',
    },
    # Railway pone exactamente UN proxy/edge delante del contenedor, que es
    # quien agrega la IP real del visitante al final de X-Forwarded-For. Con
    # NUM_PROXIES=1, DRF confía solo en ese último valor (no en lo que un
    # cliente malicioso pueda inventarse al principio del header), así cada
    # visitante real tiene su propio cupo de throttle en vez de compartir el
    # de la IP interna del proxy. Sin proxy delante (runserver local) no
    # cambia nada: sin X-Forwarded-For, DRF sigue usando REMOTE_ADDR igual.
    'NUM_PROXIES': 1,
}
